apiVersion: v1
kind: Service
metadata:
  name: mailcatcher
  labels:
    {{- include "mailcatcher.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mc_service.type }}
  ports:
    - port: {{ .Values.mc_service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mailcatcher.selectorLabels" . | nindent 4 }}
