apiVersion: v1
kind: Service
metadata:
  name: postfix
  labels:
    {{- include "mailcatcher.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postfix_service.type }}
  ports:
    - port: {{ .Values.postfix_service.port }}
      targetPort: smtp
      protocol: TCP
      name: smtp
  selector:
    {{- include "mailcatcher.selectorLabels" . | nindent 4 }}
